### ISSUE TITLE
Bug with 480p graphic pack

### ISSUE THREAD

**Issue by Luke7930** [nosklo/cemu_utils#5]
When i enter 480p in res.txt , it didn't install 480p graphic pack.

**Comment by nosklo** [comment]
Hi, thanks for your report. There was a bug with detecting 480p resolution in beta1. Are you using the beta2? 

If you are, can you please attach your `upd_cemu.json` file so I can take a look at it? It might reveal what is going on.

**Comment by Luke7930** [comment]
Yes, i use the beta 2 version.

[upd-cemu.zip](https://github.com/nosklo/cemu_utils/files/1799255/upd-cemu.zip)

**Comment by nosklo** [comment]
Okay, thanks for the files, this bug is confirmed. I will fix it

**Comment by nosklo** [comment]
Bug is fixed, next release will have the fix, or you can run it from source.
